/**
 * Components to package and distribute in Npm.
 */
import { classDefault, type ClassDefaultType } from "./class";
import {
  colorHexCheck,
  type ColorHexCheckType,
  colorHexExpand,
  type ColorHexExpandType,
  colorHexRegex,
  colorRandom,
  colorBrightnessRandom,
  type ColorBrightnessRandomType,
  colorSimilar,
  type ColorSimilarType,
} from "./color";
import {
  dateCheck,
  type DateCheckType,
  dateGet,
  type DateGetType,
  dateGetYear,
  type DateGetYearType,
  dateToLinux,
  type DateToLinuxType,
} from "./date";
import { emailCheck, type EmailCheckType, emailRegex } from "./email";
import { idDefault, type IdDefaultType } from "./id";
import {
  feetToMeters,
  type FeetToMetersType,
  metersToFeet,
  type MetersToFeetType,
} from "./length";
import {
  numberIs,
  type NumberIsType,
  numberIsPair,
  type NumberIsPairType,
  numberIsPositive,
  type NumberIsPositiveType,
  numberRandom,
  type NumberRandomType,
  numberToBoolean,
  type NumberToBooleanType,
  numberToString,
  type NumberToStringType,
  twoDecimal,
  type TwoDecimalType,
  twoDecimalsString,
  type TwoDecimalsStringType,
} from "./number";
import {
  kphToMph,
  type KphToMphType,
  mphToKph,
  type MphToKphType,
} from "./speed";
import {
  stringContainLetter,
  type StringContainLetterType,
  stringContainLetterExtent,
  type StringContainLetterExtentType,
  stringContainLetterExtentRegex,
  stringContainLetterRegex,
  stringContainLowercase,
  type StringContainLowercaseType,
  stringContainLowercaseRegex,
  stringContainNumber,
  type StringContainNumberType,
  stringContainNumberRegex,
  stringContainSpace,
  type StringContainSpaceType,
  stringContainSpaceRegex,
  stringContainSymbol,
  type StringContainSymbolType,
  stringContainSymbolRegex,
  stringContainUppercase,
  type StringContainUppercaseType,
  stringContainUppercaseRegex,
  stringIs,
  type StringIsType,
  stringIsCapital,
  type StringIsCapitalType,
  stringIsCapitalRegex,
  stringIsLetterExtentRegex,
  stringIsLetter,
  type StringIsLetterType,
  stringIsLetterExtent,
  StringIsLetterExtentType,
  stringIsLetterRegex,
  stringIsLowercase,
  type StringIsLowercaseType,
  stringIsLowercaseRegex,
  stringIsNumber,
  type StringIsNumberType,
  stringIsNumberRegex,
  stringIsSpace,
  type StringIsSpaceType,
  stringIsSpaceRegex,
  stringIsSymbol,
  type StringIsSymbolType,
  stringIsSymbolRegex,
} from "./string";
import {
  celsiusToFahrenheit,
  type CelsiusToFahrenheitType,
  fahrenheitToCelsius,
  type FahrenheitToCelsiusType,
} from "./temperature";
import {
  kilogramsToPounds,
  type KilogramsToPoundsType,
  poundsToKilograms,
  type PoundsToKilogramsType,
} from "./weight";

export {
  classDefault,
  type ClassDefaultType,
  colorHexCheck,
  type ColorHexCheckType,
  colorHexExpand,
  type ColorHexExpandType,
  colorHexRegex,
  colorRandom,
  colorBrightnessRandom,
  type ColorBrightnessRandomType,
  colorSimilar,
  type ColorSimilarType,
  dateCheck,
  type DateCheckType,
  dateGet,
  type DateGetType,
  dateGetYear,
  type DateGetYearType,
  dateToLinux,
  type DateToLinuxType,
  emailCheck,
  type EmailCheckType,
  emailRegex,
  idDefault,
  type IdDefaultType,
  feetToMeters,
  type FeetToMetersType,
  metersToFeet,
  type MetersToFeetType,
  numberIs,
  type NumberIsType,
  numberIsPair,
  type NumberIsPairType,
  numberIsPositive,
  type NumberIsPositiveType,
  numberRandom,
  type NumberRandomType,
  numberToBoolean,
  type NumberToBooleanType,
  numberToString,
  type NumberToStringType,
  kphToMph,
  type KphToMphType,
  mphToKph,
  type MphToKphType,
  twoDecimal,
  type TwoDecimalType,
  twoDecimalsString,
  type TwoDecimalsStringType,
  stringContainLetter,
  type StringContainLetterType,
  stringContainLetterExtent,
  type StringContainLetterExtentType,
  stringContainLetterExtentRegex,
  stringContainLetterRegex,
  stringContainLowercase,
  type StringContainLowercaseType,
  stringContainNumber,
  type StringContainNumberType,
  stringContainLowercaseRegex,
  stringContainNumberRegex,
  stringContainSpace,
  type StringContainSpaceType,
  stringContainSpaceRegex,
  stringContainSymbol,
  type StringContainSymbolType,
  stringContainSymbolRegex,
  stringContainUppercase,
  type StringContainUppercaseType,
  stringContainUppercaseRegex,
  stringIs,
  type StringIsType,
  stringIsCapital,
  type StringIsCapitalType,
  stringIsCapitalRegex,
  stringIsLetterExtent,
  StringIsLetterExtentType,
  stringIsLetterExtentRegex,
  stringIsLetter,
  type StringIsLetterType,
  stringIsLetterRegex,
  stringIsLowercase,
  type StringIsLowercaseType,
  stringIsLowercaseRegex,
  stringIsNumber,
  type StringIsNumberType,
  stringIsNumberRegex,
  stringIsSpace,
  type StringIsSpaceType,
  stringIsSpaceRegex,
  stringIsSymbol,
  type StringIsSymbolType,
  stringIsSymbolRegex,
  celsiusToFahrenheit,
  type CelsiusToFahrenheitType,
  fahrenheitToCelsius,
  type FahrenheitToCelsiusType,
  kilogramsToPounds,
  type KilogramsToPoundsType,
  poundsToKilograms,
  type PoundsToKilogramsType,
};
